services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=vtncPGSQL@1
      - TZ=America/Sao_Paulo
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"